### ISSUE TITLE
Suggestion: Add Skiller Rankings

### ISSUE THREAD

**Issue by DNA64** [Michaelangel007/d2_cheat_sheet#18]
**Skiller GC Rankings**
| S-TIER |A-TIER  | B-TIER | C-TIER| D-TIER|
|--|--|--|--|--|
|+1 Paladin Combat Skills|+1 Assassin Traps|+1 Necromancer Summoning Spells| +1 Paladin Defensive Auras  |+1 Necromancer Curses |
|+1 Sorceress Lighting Skills  |+1 Necromancer Poison and Bone Skills  |+1 Paladin Offensive Auras |+1 Amazon Bow and Crossbow Skills  |  |
|+1 Sorceress Cold Skills  |+1 Amazon Javelin and Spear Skills |+1 Druid Shapeshifting |+1 Barbarian Combat Masteries  |  |
|+1 Sorceress Fire Skills  |+1 Druid Elemental  |+1 Druid Summoning	 |  |  |
|  |  |+1 Assassin Shadow Disciplines	 |  |  |
|  |  |+1 Assassin Martial Arts	 |  |  |
|  |  |+1 Amazon Passive Skills	 |  |  |
|  |  |+1 Barbarian Masteries |  |  |
|  |  |+1 Barbarian Warcries |  |  |

_Credit: Unknown. Data from an image shared on discord._

**Comment by Michaelangel007** [comment]
Thanks for this suggestion! Added in version 1.95.
