### ISSUE TITLE
Table for Recharging Items (TP staff example)

### ISSUE THREAD

**Issue by pairofdocs** [Michaelangel007/d2_cheat_sheet#2]
https://github.com/Michaelangel007/d2_cheat_sheet/blob/f00075497752d4f8801052b2df0e2d06bd85ef1c/index.html#L3460

Similar to the repair table, a recharge table could be useful to add

I find it useful to recharge a teleport staff early on with

`1 Ort Rune + 1 Chipped Gem (any kind) + Weapon = Fully Repaired and Recharged Weapon `

Maybe this can be merged into the 'repair' table since the recipe is `repair + recharge`. But visually having 'recharge' be significant would be nice, so differentiating it from a regular 'repair' section would work too 🤔

**Comment by Michaelangel007** [comment]
Great suggestion!

Now live in version 1.22

**Comment by pairofdocs** [comment]
Lookin cool 😎
