### ISSUE TITLE
Small CSS Suggestion - Hide scrollbars

### ISSUE THREAD

**Issue by BICEPSSSSSSSS** [Michaelangel007/d2_cheat_sheet#21]
Here in 2021 I have this open on it's own screen off to the side in a fullscreen browser window.  Maybe it's just me but the scrollbars are ugly and not really necessary for this .  My suggestion is to add a toggle to hide the scrollbars from view.  In chrome it's as easy as below.  For now I just have a custom css applied automatically, but maybe you're bored and wanna add polish.  

```
::-webkit-scrollbar {
    display: none;
}
```

**Comment by Michaelangel007** [comment]
Added in version 1.97.

At the top of the document to the right of the `Collapse` button I added this button `[↕ ]` which will toggle hiding the scroll bars.  Tested in Chrome on Windows 10.

Thanks again for this suggestion and the initial CSS which allowed me to track down a pure `.js` solution. (It requires a nested container, with the overlay, width, and height set.)
