### ISSUE TITLE
Link for README in HtmlPreview is incorrect

### ISSUE THREAD

**Issue by derectoverso** [Michaelangel007/d2_cheat_sheet#26]
The link for the README at the bottom of the HtmlPreview seems incorrect. It redirect to the HtmlPreview.

Here is the link used at the moment: https://htmlpreview.github.io/?https://github.com/Michaelangel007/d2_cheat_sheet/blob/master/index.html#wishlist

Here is the correct link that should be on the button: https://github.com/Michaelangel007/d2_cheat_sheet#wishlist

**Comment by derectoverso** [comment]
I did some reaserch about this issue and it seems to be a common issue with HTMLPreview.
Here is an issue directly from the HTMLPreview repo: [Issue #43](https://github.com/htmlpreview/htmlpreview.github.com/issues/43)

I suggest to use an URL shortener to avoid this, here is the BitLy one: https://bit.ly/3jQigvp

**Comment by Michaelangel007** [comment]
Closing as this was fixed a while ago:

```
You can find a roadmap / wishlist of features in the <a href="https://github.com/Michaelangel007/d2_cheat_sheet#wishlist">Readme</a>.
```

I have no plans to use an URL shortener as they make it harder to identity an URL is legit.
