### ISSUE TITLE
Outdated data displayed on iOS

### ISSUE THREAD

**Issue by TrangOul** [Michaelangel007/d2_cheat_sheet#43]
On computer I can see D2R data (such as new area 85 areas), but on iPhone I see only the legacy data. It is reflected in the code as classes `ios-hidden` and `ios-visible` respectively. The former has new data, the latter is outdated.
Please update the mobile part, or, better, merge the tables so there is only one source of data and control how is it displayed by using RWD.

**Comment by Michaelangel007** [comment]
Thanks for the bug report!  Fixed in v1.72.

**Comment by Michaelangel007** [comment]
Ah, RWD = Responsive Web Design.  Thanks for the tip.  Something to look into in the future.
