### ISSUE TITLE
Persistent Collapse State

### ISSUE THREAD

**Issue by igopow** [Michaelangel007/d2_cheat_sheet#47]
I can't get the collapse state for each table to save or stay persistent after closing the cheatsheet. I'm using the original url but with my forked version instead.  Could anyone let me know what I'm doing wrong?

**Comment by Michaelangel007** [comment]
Unfortunately table state is saved (yet).  It is on the long term roadmap.

**Comment by Michaelangel007** [comment]
Collapsed table state is now persistent with v1.84.
