### ISSUE TITLE
Remove Act 5 merc from Faster Hit Recovery table

### ISSUE THREAD

**Issue by tomasz1986** [Michaelangel007/d2_cheat_sheet#48]
The Act 5 merc has no faster hit recovery animation, so it can't be put into hit recovery period (e.g. see https://reddit.com/r/ProjectDiablo2/comments/kpmqnc/act5_merc_guide and https://forums.d2jsp.org/topic.php?t=83866670&f=87). Because of this, the breakpoints exist only on paper, yet they have zero effect in the game itself.

**Comment by Michaelangel007** [comment]
Thanks for the bugfix!
