### ISSUE TITLE
Z-Index on mobile broken

### ISSUE THREAD

**Issue by Korndaweizen** [Michaelangel007/d2_cheat_sheet#52]
It appears as if the z-index of the runewords is broken for those with runes not marked as acquired yet
![Screenshot_20230303_093402_Chrome](https://user-images.githubusercontent.com/9819382/222671666-98fe4462-c59e-46cd-9361-f556ff79af75.jpg)

**Comment by Korndaweizen** [comment]
See PR #53

**Comment by Michaelangel007** [comment]
Thanks for tracking that down!  Added you to the credits.
