### ISSUE TITLE
QUESTION: Ho do you get the colorful formatting?

### ISSUE THREAD

**Issue by dwolf42** [Michaelangel007/d2_cheat_sheet#56]
Hey, I'm curious how you got all these cool colors for your page? https://htmlpreview.github.io/?https://github.com/Michaelangel007/d2_cheat_sheet/blob/master/index.html

Is it any kind of plugin or something?
I'm looking for a way to have colorful text-/-backgrounds.

I would appreciate it very much if you could kindly guide me on how to achieve this.

Cheers
David

**Comment by sir-wilhelm** [comment]
The colors are all defined in the style block at the top of the html file (starts [here](https://github.com/Michaelangel007/d2_cheat_sheet/blob/master/index.html#L7)).

The styles are applied to the various elements by setting the class in their respective HTML. You should be able to right click any element on the page and click "Inspect" to see what class is defined on the element and you can look it up in the style block to see how it's defined (or view the active styles).

**Comment by Michaelangel007** [comment]
Sorry for the late reply.

It is just plain CSS for colors. The styles are all defined near the top of the `.html`.

**Comment by Michaelangel007** [comment]
Additionally, one can either hard-code the style or programmatically assign a style to an HTML element.

For example, [updateHolyGrailButton()](https://github.com/Michaelangel007/d2_cheat_sheet/blob/master/index.html#L2942-L2971) dynamically sets CSS on a button:

```html
<style>
    .mis
    {
        color      : #F00;
        font-weight: bold;
    }

    .own
    {
        color: #080;
    }
</style>
```

```js
    var colorize =
    [
        "mis", // Missing = red
        "own", // OWned   = green
    ];

    if (state >= 0)
    {
        button.textContent = FAVS[ state ];

        _removeClasses( button, 'mis own' );
        _addClasses( button, colorize[ state ] );
    }
```

Hope this helps.
